baseURL = "https://heuristic-lewin-ba4539.netlify.com/"
languageCode = "en-us"
title = "Pack 959"

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

[params]
  # You can use Markdown syntax for urls [text](//url.to/source)
  # To create multi-line text in strings use the """example Text""" format
  #
  # All icons using Fontawesome's icon font. Look at fontawesome.io/icons
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # Provide your metadata here.
  name = "Your name"
  description = "Your description"

  # Link custom assets relative to /static
  custom_css = [
    "css/custom.css"
  ]
  custom_js  = []
  favicon    = "favicon.ico"

  # Just a custom image variable, please define it in .md files for content.
  image = ""

  # 404 error customization
  [params.error404]
    heading = "Page not found"
    text = "Please visit [this page](/)"

  # Navigation Section
  [params.navigation]
    title = "Cub Scout Pack 959"
    subtitle = ""
    menu = "Menu"

    [[params.navigation.links]]
      name = "Home"
      url = "#"

    [[params.navigation.links]]
      name = "Contact"
      url = "contact"

    [[params.navigation.links]]
      name = "Volunteer"
      url = "volunteer"

 # Footer section
  [params.footer]
    enable = true
    copyright = "Cub Scout Pack 959"

    [[params.footer.social]]
      icon = "fa-facebook"
      url= "https://www.facebook.com/familyscouting959"
      label = "Facebook"

    [[params.footer.social]]
      icon = "fa-instagram"
      url= "https://www.instagram.com/pack959"
      label = "Instagram"