baseURL = "https://heuristic-lewin-ba4539.netlify.com/"
title = "Pack 959"

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

[params]

  # Navigation Section
  [params.navigation]
    [[params.navigation.links]]
      name = "Home"
      url = "#"
    [[params.navigation.links]]
      name = "Contact"
      url = "contact"
    [[params.navigation.links]]
      name = "Volunteer"
      url = "volunteer"

  # Home
  [params.home]

    ## Why Cub Scouts?
    [params.home.why]
      title = "Why Cub Scouts?"
      [[params.home.why.box]]
        title = "Build Character"
        text = "Cub Scouts build character through a collection of core values by an individual that leads to moral commitment and action.  A Scout is Trustworthy, Loyal, Helpful, Friendly, Courteous, Kind, Obedient, Cheerful, Thrifty, Brave, Clean and Reverent."
      [[params.home.why.box]]
        title = "Learn Citizenship"
        text = "Cub Scouts learn citizenship means contributing service and showing responsibility to local, state, and national communities.  By helping fellow citizens in our local community, we remember the Law of the Pack and what it means when we say \"gives goodwill.\""
      [[params.home.why.box]]
        title = "Mental and Physical Fitness"
        text = "Cub Scouts learn to become personally committed to keeping their minds and bodies clean and fit.  A Scout know they needs to be strong and healthy in mind and body to be able to contribute to our family, community, and nation."

    [params.home.activities]
      title = "Activities"
      subtitle = ""
      [[params.home.activities.item]]
        image = "images/camping.jpg"
        title = "Camping"
        text = "Eget mi ac magna cep lobortis faucibus accumsan enim lacinia adipiscing metus urna adipiscing cep commodo id. Ac quis arcu amet. Arcu nascetur lorem adipiscing non faucibus odio nullam arcu lobortis. Aliquet ante feugiat. Turpis aliquet ac posuere volutpat lorem arcu aliquam lorem."
        url = "#"
      [[params.home.activities.item]]
        image = "images/flag_planting.jpg"
        title = "Community Service"
        text = "Eget mi ac magna cep lobortis faucibus accumsan enim lacinia adipiscing metus urna adipiscing cep commodo id. Ac quis arcu amet. Arcu nascetur lorem adipiscing non faucibus odio nullam arcu lobortis. Aliquet ante feugiat. Turpis aliquet ac posuere volutpat lorem arcu aliquam lorem."
        url = "#"
      [[params.home.activities.item]]
        image = "images/bow.jpg"
        title = "Outdoor Sports"
        text = "Eget mi ac magna cep lobortis faucibus accumsan enim lacinia adipiscing metus urna adipiscing cep commodo id. Ac quis arcu amet. Arcu nascetur lorem adipiscing non faucibus odio nullam arcu lobortis. Aliquet ante feugiat. Turpis aliquet ac posuere volutpat lorem arcu aliquam lorem."
        url = "#"
      [[params.home.activities.item]]
        image = "images/pwd.jpg"
        title = "Pinewood Derby"
        text = "Eget mi ac magna cep lobortis faucibus accumsan enim lacinia adipiscing metus urna adipiscing cep commodo id. Ac quis arcu amet. Arcu nascetur lorem adipiscing non faucibus odio nullam arcu lobortis. Aliquet ante feugiat. Turpis aliquet ac posuere volutpat lorem arcu aliquam lorem."
        url = "#"

    # Resources
    [[params.home.resources]]
      text = "5 Things To Know Before Starting Cub Scouts"
      url = "https://cubscouts.org/5-things-know-starting-cub-scouts/"
    [[params.home.resources]]
      text = "The Lion program"
      url = "http://scoutingwire.org/lion/"
    [[params.home.resources]]
      text = "Guide to uniforms"
      url = "http://www.bsauniforms.org/"
    [[params.home.resources]]
      text = "Insignia"
      url = "https://filestore.scouting.org/filestore/pdf/CubScout_Insignia.pdf"
    [[params.home.resources]]
      text = "ScoutBook"
      url = "https://www.scoutbook.com/"

 # Footer section
  [params.footer]
    copyright = "Cub Scout Pack 959"

    [[params.footer.social]]
      icon = "fa-facebook"
      url = "https://www.facebook.com/familyscouting959"
      label = "Facebook"
    [[params.footer.social]]
      icon = "fa-instagram"
      url = "https://www.instagram.com/pack959"
      label = "Instagram"