title = "Pack 959 - Hockessin, Delaware"
baseURL = "https://www.pack959.com/"
googleAnalytics = "UA-145912342-1"

disableKinds = ["taxonomy", "taxonomyTerm", "RSS"]
enableRobotsTXT = true

theme = ["pack959"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

## Menus
[[ menu.main ]]
title = "Home"
url = "/"
identifier = "index"
weight = 10

[[ menu.main ]]
title = "Calendar"
url = "/calendar/"
identifier = "calendar"
weight = 20

[[ menu.main ]]
title = "Contact"
url = "/contact/"
identifier = "contact"
weight = 30

[[ menu.main ]]
title = "Volunteer"
url = "/volunteer/"
identifier = "volunteer"
weight = 40

[[ menu.main ]]
title = "Join"
url = "/join/"
identifier = "join"
weight = 100

## Submenus
[[ menu.main ]]
title = "Pack"
url = "/calendar/"
identifier = "pack"
weight = 10
parent = "calendar"

[[ menu.main ]]
title = "Dens"
url = "#"
weight = 20
identifier = "dens"
parent = "calendar"

    [[ menu.main ]]
    title = "Lion"
    url = "/calendar/lion/"
    weight = 10
    identifier = "lion"
    parent = "dens"

    [[ menu.main ]]
    title = "Tiger"
    url = "/calendar/tiger/"
    weight = 20
    identifier = "tiger"
    parent = "dens"

    [[ menu.main ]]
    title = "Wolf"
    url = "/calendar/wolf/"
    weight = 30
    identifier = "wolf"
    parent = "dens"

    [[ menu.main ]]
    title = "Bear"
    url = "/calendar/bear/"
    weight = 40
    identifier = "bear"
    parent = "dens"

    [[ menu.main ]]
    title = "Webelos"
    url = "/calendar/webelos/"
    weight = 50
    identifier = "webelos"
    parent = "dens"

    [[ menu.main ]]
    title = "Arrow of Light"
    url = "/calendar/aol/"
    weight = 60
    identifier = "aol"
    parent = "dens"

[[ menu.main ]]
title = "Leader"
url = "/calendar/leader/"
weight = 30
identifier = "leader"
parent = "calendar"

[[ menu.main ]]
title = "All Events"
url = "/calendar/all/"
weight = 40
identifier = "all"
parent = "calendar"