[build]
publish = "public"
command = "hugo --minify"

[build.environment]
HUGO_VERSION = "0.48"
#HUGO_ENABLEGITINFO = "true"

[context.production.environment]
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --buildFuture --baseURL $DEPLOY_PRIME_URL"

[context.staging]
command = "hugo --buildFuture --baseURL $DEPLOY_PRIME_URL"
