[build]
publish = "public"
functions = "functions"
command = "make"

[build.environment]
HUGO_VERSION = "0.57.2"
GO_VERSION = "1.12"
TZ = "America/New_York"

[context.production.environment]
HUGO_ENV = "production"

[context.deploy-preview]
environment = { HUGOARGS = "--buildFuture --baseURL $(DEPLOY_PRIME_URL)" }

# Redirects
[[redirects]]
  from = "/advancements"
  to = "/"

[[redirects]]
  from = "/kindergartners-and-cub-scouts"
  to = "/"

[[redirects]]
  from = "/family-involvement"
  to = "/"

[[redirects]]
  from = "/gallery/*"
  to = "/"

[[redirects]]
  from = "/resources"
  to = "/"

[[redirects]]
  from = "/why-scouting"
  to = "/"

[[redirects]]
  from = "/talent"
  to = "https://docs.google.com/forms/d/e/1FAIpQLSfmF1ONKOQh7Dfe587QInviTI8LRW040aKGxci9FrWmFZTBCA/viewform?usp=sf_link"
