backend:
  name: git-gateway
  branch: master

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "Pages"
    label: "pages"
    files:
      - file: "content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: Why, name: why, widget: object, fields: [
              {label: Heading, name: heading, widget: string},
              {label: Items, name: items, widget: list, fields: [ 
                {label: Title, name: title, widget: string},
                {label: Text, name: text, widget: text}]}]}
          - {label: Activities, name: activities, widget: object, fields: [
              {label: Title, name: title, widget: string},
              {label: Subtitle, name: subtitle, widget: string},
              {label: Items, name: items, widget: list, fields: [ 
                {label: Title, name: title, widget: string},
                {label: Image, name: image, widget: image},
                {label: Text, name: text, widget: text},
                {label: Url, name: url, widget: string}]}]}
          - {label: Resources, name: resources, widget: list, fields: [ 
              {label: Text, name: text, widget: string},
              {label: Url, name: url, widget: string}]}

      - file: "content/join.md"
        label: "Join"
        name: "join"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}

      - file: "content/volunteer.md"
        label: "Volunteer"
        name: "volunteer"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}